# DO NOT EDIT THIS FILE !!! ( ｡ •̀ ᴖ •́ ｡)
# ITS AUTOMATICALLY GENERATED BY RUNNING ./dev/generate_anilist_media_tags.py
# FROM THE PROJECT ROOT
# SO RUN THAT INSTEAD TO UPDATE THE FILE WITH THE LATEST MEDIA TAGS :)


from enum import Enum


class MediaTag(Enum):
    #
    # TECHNICAL
    #

    # A manga in the 'yonkoma' format, which consists of four equal-sized panels arranged in a vertical strip. (is_adult: False)
    _4_KOMA = "4-koma"

    # Contains animation that is primarily done in black and white. (is_adult: False)
    ACHROMATIC = "Achromatic"

    # Produced in order to promote the products of a certain company. (is_adult: False)
    ADVERTISEMENT = "Advertisement"

    # A collection of separate works collated into a single release. (is_adult: False)
    ANTHOLOGY = "Anthology"

    # Prominently features scenes created with computer-generated imagery. (is_adult: False)
    CGI = "CGI"

    # Features story arcs that are loosely tied or lack an overarching plot. (is_adult: False)
    EPISODIC = "Episodic"

    # Created using Flash animation techniques. (is_adult: False)
    FLASH = "Flash"

    # Almost entirely created with computer-generated imagery. (is_adult: False)
    FULL_CGI = "Full CGI"

    # Manga that were initially published in full color. (is_adult: False)
    FULL_COLOR = "Full Color"

    # Manga originally published in a vertical, long-strip format, designed for viewing on smartphones. Also known as webtoons. (is_adult: False)
    LONG_STRIP = "Long Strip"

    # Features a combination of different media and animation techniques. Often seen with puppetry, textiles, live action footage, stop motion, and more. This does not include works with normal usage of CGI in their production. (is_adult: False)
    MIXED_MEDIA = "Mixed Media"

    # This work contains no dialogue. (is_adult: False)
    NO_DIALOGUE = "No Dialogue"

    # A work that provides information regarding a real world topic and does not focus on an imaginary narrative. (is_adult: False)
    NON_FICTION = "Non-fiction"

    # Point of View; features scenes shown from the perspective of the series protagonist. (is_adult: False)
    POV = "POV"

    # Animation style involving the manipulation of puppets to act out scenes. (is_adult: False)
    PUPPETRY = "Puppetry"

    # Animation technique that animators use to trace over motion picture footage, frame by frame, to produce realistic action. (is_adult: False)
    ROTOSCOPING = "Rotoscoping"

    # Animation style characterized by physical objects being moved incrementally between frames to create the illusion of movement. (is_adult: False)
    STOP_MOTION = "Stop Motion"

    # Animated works originally created in a vertical aspect ratio (such as 9:16), intended for viewing on smartphones. (is_adult: False)
    VERTICAL_VIDEO = "Vertical Video"

    #
    # SETTING-TIME
    #

    # Chapters or episodes do not occur in chronological order. (is_adult: False)
    ACHRONOLOGICAL_ORDER = "Achronological Order"

    # Prominently features elements that are out of place in the historical period the work takes place in, particularly modern elements in a historical setting. (is_adult: False)
    ANACHRONISM = "Anachronism"

    # Setting in ancient china, does not apply to fantasy settings. (is_adult: False)
    ANCIENT_CHINA = "Ancient China"

    # Partly or completely set in a society characterized by poverty, squalor or oppression. (is_adult: False)
    DYSTOPIAN = "Dystopian"

    # Partly or completely set during a real period of world history. (is_adult: False)
    HISTORICAL = "Historical"

    # Partially or completely set in the Middle Ages or a Middle Ages-inspired setting. Commonly features elements such as European castles and knights. (is_adult: False)
    MEDIEVAL = "Medieval"

    # Features a gap in time used to advance the story. (is_adult: False)
    TIME_SKIP = "Time Skip"

    #
    # THEME-GAME-SPORT
    #

    # The art of jumping, tumbling, and balancing. Often paired with trapeze, trampolining, tightropes, or general gymnastics. (is_adult: False)
    ACROBATICS = "Acrobatics"

    # Centers around the sport of airsoft. (is_adult: False)
    AIRSOFT = "Airsoft"

    # Centers around the sport of American football. (is_adult: False)
    AMERICAN_FOOTBALL = "American Football"

    # Centers around sporting events that involve competitive running, jumping, throwing, or walking. (is_adult: False)
    ATHLETICS = "Athletics"

    # Centers around the sport of badminton. (is_adult: False)
    BADMINTON = "Badminton"

    # Centers around the sport of baseball. (is_adult: False)
    BASEBALL = "Baseball"

    # Centers around the sport of basketball. (is_adult: False)
    BASKETBALL = "Basketball"

    # Centers around the sport of Bowling. (is_adult: False)
    BOWLING = "Bowling"

    # Centers around the sport of boxing. (is_adult: False)
    BOXING = "Boxing"

    # Centers around the activity of cheerleading. (is_adult: False)
    CHEERLEADING = "Cheerleading"

    # Centers around the sport of cycling. (is_adult: False)
    CYCLING = "Cycling"

    # Centers around the sport of fencing. (is_adult: False)
    FENCING = "Fencing"

    # Centers around the sport of fishing. (is_adult: False)
    FISHING = "Fishing"

    # Centers around exercise with the aim of improving physical health. (is_adult: False)
    FITNESS = "Fitness"

    # Centers around the sport of football (known in the USA as "soccer"). (is_adult: False)
    FOOTBALL = "Football"

    # Centers around the sport of golf. (is_adult: False)
    GOLF = "Golf"

    # Centers around the sport of handball. (is_adult: False)
    HANDBALL = "Handball"

    # Centers around the sport of ice skating. (is_adult: False)
    ICE_SKATING = "Ice Skating"

    # Centers around the sport of judo. (is_adult: False)
    JUDO = "Judo"

    # A team game played with a ball and lacrosse sticks. (is_adult: False)
    LACROSSE = "Lacrosse"

    # Centers around the sport of parkour. (is_adult: False)
    PARKOUR = "Parkour"

    # Centers around the sport of rugby. (is_adult: False)
    RUGBY = "Rugby"

    # Prominently features characters diving with the aid of special breathing equipment. (is_adult: False)
    SCUBA_DIVING = "Scuba Diving"

    # Centers around or prominently features skateboarding as a sport. (is_adult: False)
    SKATEBOARDING = "Skateboarding"

    # Centers around the sport of sumo. (is_adult: False)
    SUMO = "Sumo"

    # Centers around surfing as a sport. (is_adult: False)
    SURFING = "Surfing"

    # Centers around the sport of swimming. (is_adult: False)
    SWIMMING = "Swimming"

    # Centers around the sport of table tennis (also known as "ping pong"). (is_adult: False)
    TABLE_TENNIS = "Table Tennis"

    # Centers around the sport of tennis. (is_adult: False)
    TENNIS = "Tennis"

    # Centers around the sport of volleyball. (is_adult: False)
    VOLLEYBALL = "Volleyball"

    # Centers around the sport of wrestling. (is_adult: False)
    WRESTLING = "Wrestling"

    #
    # THEME-ARTS
    #

    # Centers around actors or the acting industry. (is_adult: False)
    ACTING = "Acting"

    # Prominently features the dance art of ballet. Both traditional and contemporary styles. (is_adult: False)
    BALLET = "Ballet"

    # Centers around the art of calligraphy. (is_adult: False)
    CALLIGRAPHY = "Calligraphy"

    # Discusses or adapts a work of classic world literature. (is_adult: False)
    CLASSIC_LITERATURE = "Classic Literature"

    # Centers around the art of drawing, including manga and doujinshi. (is_adult: False)
    DRAWING = "Drawing"

    # Centers around the fashion industry. (is_adult: False)
    FASHION = "Fashion"

    # Centers around cooking or food appraisal. (is_adult: False)
    FOOD = "Food"

    # Prominently features the traditional Japanese theater art of kabuki. (is_adult: False)
    KABUKI = "Kabuki"

    # Centers around the makeup industry. (is_adult: False)
    MAKEUP = "Makeup"

    # Prominently features an act of traditional Japanese comedy that involves two performers. (is_adult: False)
    MANZAI = "Manzai"

    # Features a line of work with the purpose of displaying and advertising products such as makeup, clothing, and jewelry. Also includes posing artistically for figure drawing, painting, sculpting, and photography. (is_adult: False)
    MODELING = "Modeling"

    # Centers around the use of cameras to capture photos. (is_adult: False)
    PHOTOGRAPHY = "Photography"

    # Rakugo is the traditional Japanese performance art of comic storytelling. (is_adult: False)
    RAKUGO = "Rakugo"

    # Centers around the profession of writing books or novels. (is_adult: False)
    WRITING = "Writing"

    #
    # THEME-OTHER
    #

    # Features a character who has been adopted by someone who is neither of their biological parents. (is_adult: False)
    ADOPTION = "Adoption"

    # Prominently features animal characters in a leading role. (is_adult: False)
    ANIMALS = "Animals"

    # Relating or centered around the study of celestial objects and phenomena, space, or the universe. (is_adult: False)
    ASTRONOMY = "Astronomy"

    # Real stories and anecdotes written by the author about their own life. (is_adult: False)
    AUTOBIOGRAPHICAL = "Autobiographical"

    # Based on true stories of real persons living or dead, written by another. (is_adult: False)
    BIOGRAPHICAL = "Biographical"

    # Features a character blackmailing another. (is_adult: False)
    BLACKMAIL = "Blackmail"

    # Features characters who undergo horrific transformations or disfigurement, often to their own detriment. (is_adult: False)
    BODY_HORROR = "Body Horror"

    # Features themes of self-esteem concerning perceived defects or flaws in appearance, such as body weight or disfigurement, and may discuss topics such as eating disorders, fatphobia, and body dysmorphia. (is_adult: False)
    BODY_IMAGE = "Body Image"

    # Prominently features the act of consuming another member of the same species as food. (is_adult: False)
    CANNIBALISM = "Cannibalism"

    # Features "super deformed" character designs with smaller, rounder proportions and a cute look. (is_adult: False)
    CHIBI = "Chibi"

    # A type of horror that emphasizes human insignificance in the grand scope of cosmic reality; fearing the unknown and being powerless to fight it. (is_adult: False)
    COSMIC_HORROR = "Cosmic Horror"

    # Features the taming of animals, monsters, or other creatures. (is_adult: False)
    CREATURE_TAMING = "Creature Taming"

    # Centers around unlawful activities punishable by the state or other authority. (is_adult: False)
    CRIME = "Crime"

    # Centers around the placement of two or more otherwise discrete fictional characters, settings, or universes into the context of a single story. (is_adult: False)
    CROSSOVER = "Crossover"

    # Features characters participating in a game, where failure results in death. (is_adult: False)
    DEATH_GAME = "Death Game"

    # Works that feature themes of social dissociation, delusions, and other issues like suicide, bullying, self-isolation, paranoia, and technological necessity in daily lives. Classic iconography: telephone poles, rooftops, and trains. (is_adult: False)
    DENPA = "Denpa"

    # Prominently features the usage of drugs such as opioids, stimulants, hallucinogens etc. (is_adult: False)
    DRUGS = "Drugs"

    # Centers around the field of economics. (is_adult: False)
    ECONOMICS = "Economics"

    # Primary aim is to educate the audience. (is_adult: False)
    EDUCATIONAL = "Educational"

    # Concern with the state of the natural world and how humans interact with it. (is_adult: False)
    ENVIRONMENTAL = "Environmental"

    # Japanese literary and artistic movement originating in the 1930's. Works have a focus on grotesque eroticism, sexual corruption, and decadence. (is_adult: False)
    ERO_GURO = "Ero Guro"

    # Centers around the art of filmmaking. (is_adult: False)
    FILMMAKING = "Filmmaking"

    # Features a group of characters with no biological relations that are united in a group providing social support. (is_adult: False)
    FOUND_FAMILY = "Found Family"

    # Centers around the act of gambling. (is_adult: False)
    GAMBLING = "Gambling"

    # Prominently features a character who dresses and behaves in a way characteristic of another gender, or has been transformed into a person of another gender. (is_adult: False)
    GENDER_BENDING = "Gender Bending"

    # Prominently features graphic bloodshed and violence. (is_adult: False)
    GORE = "Gore"

    # Prominently features real-life indigenous cultures. (is_adult: False)
    INDIGENOUS_CULTURES = "Indigenous Cultures"

    # A barrier to communication between people who are unable to speak a common language. (is_adult: False)
    LANGUAGE_BARRIER = "Language Barrier"

    # Prominently features characters or themes associated with the LGBTQ+ community, such as sexuality or gender identity. (is_adult: False)
    LGBTQ_THEMES = "LGBTQ+ Themes"

    # Featuring a civilization with few ruins or records that exist in present day knowledge. (is_adult: False)
    LOST_CIVILIZATION = "Lost Civilization"

    # Centers around marriage between two or more characters. (is_adult: False)
    MARRIAGE = "Marriage"

    # Centered around the activities of people working in the field of medicine. (is_adult: False)
    MEDICINE = "Medicine"

    # Prominently features a character(s) who has had their memories altered. (is_adult: False)
    MEMORY_MANIPULATION = "Memory Manipulation"

    # Features fourth wall-breaking references to itself or genre tropes. (is_adult: False)
    META = "Meta"

    # Prominently features characters discussing or hiking mountains. (is_adult: False)
    MOUNTAINEERING = "Mountaineering"

    # Stylized as a cynical crime drama with low-key visuals. (is_adult: False)
    NOIR = "Noir"

    # Centers around the culture of a fanatical fan-base. (is_adult: False)
    OTAKU_CULTURE = "Otaku Culture"

    # Prominently features a disease prevalent over a whole country or the world. (is_adult: False)
    PANDEMIC = "Pandemic"

    # Relating or devoted to the study of the fundamental nature of knowledge, reality, and existence. (is_adult: False)
    PHILOSOPHY = "Philosophy"

    # Centers around politics, politicians, or government activities. (is_adult: False)
    POLITICS = "Politics"

    # Features pregnant female characters or discusses the topic of pregnancy. (is_adult: False)
    PREGNANCY = "Pregnancy"

    # A proxy battle is a battle where humans use creatures/robots to do the fighting for them, either by commanding those creatures/robots or by simply evolving them/changing them into battle mode. (is_adult: False)
    PROXY_BATTLE = "Proxy Battle"

    # Work that involves the psychological aspects of sexual impulses. (is_adult: False)
    PSYCHOSEXUAL = "Psychosexual"

    # Features a character being born again after death, typically as another person or in another world. (is_adult: False)
    REINCARNATION = "Reincarnation"

    # Centers on the belief that humanity is related to supernatural, transcendental, and spiritual elements. (is_adult: False)
    RELIGION = "Religion"

    # Centers around operations that carry out urgent treatment of injuries, remove people from danger, or save lives. This includes series that are about search-and-rescue teams, trauma surgeons, firefighters, and more. (is_adult: False)
    RESCUE = "Rescue"

    # Features nobility, alliances, arranged marriage, succession disputes, religious orders and other elements of royal politics. (is_adult: False)
    ROYAL_AFFAIRS = "Royal Affairs"

    # Prominently features slaves, slavery, or slave trade. (is_adult: False)
    SLAVERY = "Slavery"

    # Centers around characters developing or programming a piece of technology, software, gaming, etc. (is_adult: False)
    SOFTWARE_DEVELOPMENT = "Software Development"

    # Centers around the struggle to live in spite of extreme obstacles. (is_adult: False)
    SURVIVAL = "Survival"

    # Centers around the activities of a terrorist or terrorist organization. (is_adult: False)
    TERRORISM = "Terrorism"

    # The act of deliberately inflicting severe pain or suffering upon another individual or oneself as a punishment or with a specific purpose. (is_adult: False)
    TORTURE = "Torture"

    # Centers around character(s) moving between places a significant distance apart. (is_adult: False)
    TRAVEL = "Travel"

    # Features one or more singers or characters that are products of a synthesize singing program. Popular examples are Vocaloids, UTAUloids, and CeVIOs. (is_adult: False)
    VOCAL_SYNTH = "Vocal Synth"

    # Partly or completely set during wartime. (is_adult: False)
    WAR = "War"

    #
    # SETTING-UNIVERSE
    #

    # Partly or completely set in the afterlife. (is_adult: False)
    AFTERLIFE = "Afterlife"

    # Features multiple alternate universes in the same series. (is_adult: False)
    ALTERNATE_UNIVERSE = "Alternate Universe"

    # Prominently features events with augmented reality as the main setting. (is_adult: False)
    AUGMENTED_REALITY = "Augmented Reality"

    # Alternative universe that prominently features dynamics modeled after wolves in which there are alphas, betas, and omegas and heat cycles as well as impregnation, regardless of gender. (is_adult: True)
    OMEGAVERSE = "Omegaverse"

    # Partly or completely set in a world or civilization after a global disaster. (is_adult: False)
    POST_APOCALYPTIC = "Post-Apocalyptic"

    # Partly or completely set in outer space. (is_adult: False)
    SPACE = "Space"

    # Set in a world similar to the real world, but with the existence of magic or other supernatural elements. (is_adult: False)
    URBAN_FANTASY = "Urban Fantasy"

    # Partly or completely set in the world inside a video game. (is_adult: False)
    VIRTUAL_WORLD = "Virtual World"

    #
    # THEME-ROMANCE
    #

    # Prominently features romantic relations between people with a significant age difference. (is_adult: False)
    AGE_GAP = "Age Gap"

    # Prominently features romance between two males, not inherently sexual. (is_adult: False)
    BOYS_LOVE = "Boys' Love"

    # Features two or more people who live in the same household and develop a romantic or sexual relationship. (is_adult: False)
    COHABITATION = "Cohabitation"

    # Main cast features the protagonist plus several female characters who are romantically interested in them. (is_adult: False)
    FEMALE_HAREM = "Female Harem"

    # Prominently features a romance between a man and a woman, not inherently sexual. (is_adult: False)
    HETEROSEXUAL = "Heterosexual"

    # Centered around romantic feelings between more than two people. Includes all love polygons. (is_adult: False)
    LOVE_TRIANGLE = "Love Triangle"

    # Main cast features the protagonist plus several male characters who are romantically interested in them. (is_adult: False)
    MALE_HAREM = "Male Harem"

    # Prominently features either a matchmaker or events with the intent of matchmaking with eventual marriage in sight. (is_adult: False)
    MATCHMAKING = "Matchmaking"

    # Main cast features the protagonist plus several people, regardless of gender, who are romantically interested in them. (is_adult: False)
    MIXED_GENDER_HAREM = "Mixed Gender Harem"

    # Features a character who is in a consenting relationship with multiple people at one time. (is_adult: False)
    POLYAMOROUS = "Polyamorous"

    # Sexually explicit love-story between individuals of the opposite sex, specifically targeting females of teens and young adult age. (is_adult: False)
    TEENS_LOVE = "Teens' Love"

    # One or more characters are experiencing an unrequited love that may or may not be reciprocated. (is_adult: False)
    UNREQUITED_LOVE = "Unrequited Love"

    # Prominently features romance between two females, not inherently sexual. Also known as Girls' Love. (is_adult: False)
    YURI = "Yuri"

    #
    # CAST-TRAITS
    #

    # Prominently features a character who was returned to a younger state. (is_adult: False)
    AGE_REGRESSION = "Age Regression"

    # Prominently features agender characters. (is_adult: False)
    AGENDER = "Agender"

    # Prominently features extraterrestrial lifeforms. (is_adult: False)
    ALIENS = "Aliens"

    # Prominently features a character(s) with memory loss. (is_adult: False)
    AMNESIA = "Amnesia"

    # Prominently features spiritual beings usually represented with wings and halos and believed to be attendants of God. (is_adult: False)
    ANGELS = "Angels"

    # Contains non-human character(s) that have attributes or characteristics of a human being. (is_adult: False)
    ANTHROPOMORPHISM = "Anthropomorphism"

    # Features a character who experiences little to no romantic attraction. (is_adult: False)
    AROMANTIC = "Aromantic"

    # Features two characters made to marry each other, usually by their family. (is_adult: False)
    ARRANGED_MARRIAGE = "Arranged Marriage"

    # Intelligent non-organic machines that work and react similarly to humans. (is_adult: False)
    ARTIFICIAL_INTELLIGENCE = "Artificial Intelligence"

    # Features a character who isn't sexually attracted to people of any sex or gender. (is_adult: False)
    ASEXUAL = "Asexual"

    # Features a character who is romantically or sexually attracted to people of more than one sex or gender. (is_adult: False)
    BISEXUAL = "Bisexual"

    # Prominently features a character who is a butler. (is_adult: False)
    BUTLER = "Butler"

    # Prominently features a character with a human upper body and the lower body of a horse. (is_adult: False)
    CENTAUR = "Centaur"

    # Features a beast made by combining animals, usually with humans. (is_adult: False)
    CHIMERA = "Chimera"

    # Prominently features a character with "Middle School 2nd Year Syndrome", who either acts like a know-it-all adult or falsely believes they have special powers. (is_adult: False)
    CHUUNIBYOU = "Chuunibyou"

    # Prominently features a character who is an artificial exact copy of another organism. (is_adult: False)
    CLONE = "Clone"

    # Features dressing up as a different character or profession. (is_adult: False)
    COSPLAY = "Cosplay"

    # Features Western or Western-inspired cowboys. (is_adult: False)
    COWBOYS = "Cowboys"

    # Prominently features a character dressing up as the opposite sex. (is_adult: False)
    CROSSDRESSING = "Crossdressing"

    # Prominently features a human character whose physiological functions are aided or enhanced by artificial means. (is_adult: False)
    CYBORG = "Cyborg"

    # Features characters with a notorious image and attitude, sometimes referred to as "yankees". (is_adult: False)
    DELINQUENTS = "Delinquents"

    # Prominently features malevolent otherworldly creatures. (is_adult: False)
    DEMONS = "Demons"

    # Features a character who investigates and solves crimes. (is_adult: False)
    DETECTIVE = "Detective"

    # Prominently features Dinosaurs, prehistoric reptiles that went extinct millions of years ago. (is_adult: False)
    DINOSAURS = "Dinosaurs"

    # A work that features one or more characters with a physical, mental, cognitive, or developmental condition that impairs, interferes with, or limits the person's ability to engage in certain tasks or actions. (is_adult: False)
    DISABILITY = "Disability"

    # A case where one or more people share the same body. (is_adult: False)
    DISSOCIATIVE_IDENTITIES = "Dissociative Identities"

    # Prominently features mythical reptiles which generally have wings and can breathe fire. (is_adult: False)
    DRAGONS = "Dragons"

    # Prominently features a character who is a Dullahan, a creature from Irish Folklore with a head that can be detached from its main body. (is_adult: False)
    DULLAHAN = "Dullahan"

    # Prominently features a character who is an elf. (is_adult: False)
    ELF = "Elf"

    # Prominently features a character who is a fairy. (is_adult: False)
    FAIRY = "Fairy"

    # Features a boy who exhibits characteristics or behaviors considered in many cultures to be typical of girls. (is_adult: False)
    FEMBOY = "Femboy"

    # Prominently features a character who is a ghost. (is_adult: False)
    GHOST = "Ghost"

    # A goblin is a monstrous creature from European folklore. They are almost always small and grotesque, mischievous or outright malicious, and greedy. Sometimes with magical abilities. (is_adult: False)
    GOBLIN = "Goblin"

    # Prominently features a character of divine or religious nature. (is_adult: False)
    GODS = "Gods"

    # Prominently features a female character who has a distinct American-emulated fashion style, such as tanned skin, bleached hair, and excessive makeup. Also known as gal. (is_adult: False)
    GYARU = "Gyaru"

    # Prominently features a character who withdraws from social life, often seeking extreme isolation. (is_adult: False)
    HIKIKOMORI = "Hikikomori"

    # Prominently features a character that is homeless. (is_adult: False)
    HOMELESS = "Homeless"

    # Centers around the life and activities of an idol. (is_adult: False)
    IDOL = "Idol"

    # Prominently features humanoid characters with animal ears. (is_adult: False)
    KEMONOMIMI = "Kemonomimi"

    # Prominently features a character who generally retains a cold, blunt and cynical exterior, but once one gets to know them, they have a very warm and loving interior. (is_adult: False)
    KUUDERE = "Kuudere"

    # Prominently features a character who is a maid. (is_adult: False)
    MAIDS = "Maids"

    # A mythological creature with the body of a human and the tail of a fish. (is_adult: False)
    MERMAID = "Mermaid"

    # Prominently features a male character who is a part-monster. (is_adult: False)
    MONSTER_BOY = "Monster Boy"

    # Prominently features a female character who is part-monster. (is_adult: False)
    MONSTER_GIRL = "Monster Girl"

    # Humanoid characters with cat-like features such as cat ears and a tail. (is_adult: False)
    NEKOMIMI = "Nekomimi"

    # Prominently features Japanese warriors traditionally trained in espionage, sabotage and assasination. (is_adult: False)
    NINJA = "Ninja"

    # Features a character wearing no clothing or exposing intimate body parts. (is_adult: False)
    NUDITY = "Nudity"

    # Prominently features a character who is a nun. (is_adult: False)
    NUN = "Nun"

    # Prominently features a female office worker or OL. (is_adult: False)
    OFFICE_LADY = "Office Lady"

    # Prominently features a courtesan character of the Japanese Edo Period. (is_adult: False)
    OIRAN = "Oiran"

    # Features a wealthy, high-class, oftentimes stuck up and demanding female character. (is_adult: False)
    OJOU_SAMA = "Ojou-sama"

    # Prominently features a character that is an orphan. (is_adult: False)
    ORPHAN = "Orphan"

    # Prominently features sea-faring adventurers branded as criminals by the law. (is_adult: False)
    PIRATES = "Pirates"

    # Prominently features humanoid machines. (is_adult: False)
    ROBOTS = "Robots"

    # Prominently features warriors of medieval Japanese nobility bound by a code of honor. (is_adult: False)
    SAMURAI = "Samurai"

    # Prominently features a character who is a shrine maiden. (is_adult: False)
    SHRINE_MAIDEN = "Shrine Maiden"

    # Prominently features skeleton(s) as a character. (is_adult: False)
    SKELETON = "Skeleton"

    # Prominently features a character who is a succubus, a creature in medieval folklore that typically uses their sexual prowess to trap and seduce people to feed off them. (is_adult: False)
    SUCCUBUS = "Succubus"

    # Prominently features characters with tanned skin. (is_adult: False)
    TANNED_SKIN = "Tanned Skin"

    # Protagonist is an educator, usually in a school setting. (is_adult: False)
    TEACHER = "Teacher"

    # Features a girl who exhibits characteristics or behaviors considered in many cultures to be typical of boys. (is_adult: False)
    TOMBOY = "Tomboy"

    # Features a character whose gender identity differs from the sex they were assigned at birth. (is_adult: False)
    TRANSGENDER = "Transgender"

    # Prominently features a character who acts cold and hostile in order to mask warmer emotions. (is_adult: False)
    TSUNDERE = "Tsundere"

    # Prominently features two or more siblings that were born at one birth. (is_adult: False)
    TWINS = "Twins"

    # Prominently features a character who is a vampire. (is_adult: False)
    VAMPIRE = "Vampire"

    # Prominently features a veterinarian or one of the main characters is a veterinarian. (is_adult: False)
    VETERINARIAN = "Veterinarian"

    # Prominently features Scandinavian seafaring pirates and warriors. (is_adult: False)
    VIKINGS = "Vikings"

    # Centers around or prominently features a villainous noble lady. (is_adult: False)
    VILLAINESS = "Villainess"

    # Prominently features a character who is either an actual or fictive VTuber. (is_adult: False)
    VTUBER = "VTuber"

    # Prominently features a character who is a werewolf. (is_adult: False)
    WEREWOLF = "Werewolf"

    # Prominently features a character who is a witch. (is_adult: False)
    WITCH = "Witch"

    # Prominently features a character who is obsessively in love with another, to the point of acting deranged or violent. (is_adult: False)
    YANDERE = "Yandere"

    # Prominently features reanimated corpses which often prey on live humans and turn them into zombies. (is_adult: False)
    ZOMBIE = "Zombie"

    #
    # THEME-SLICE OF LIFE
    #

    # Prominently features agriculture practices. (is_adult: False)
    AGRICULTURE = "Agriculture"

    # Centers around male characters doing cute activities, usually with little to no emphasis on drama and conflict. (is_adult: False)
    CUTE_BOYS_DOING_CUTE_THINGS = "Cute Boys Doing Cute Things"

    # Centers around female characters doing cute activities, usually with little to no emphasis on drama and conflict. (is_adult: False)
    CUTE_GIRLS_DOING_CUTE_THINGS = "Cute Girls Doing Cute Things"

    # Centers around the activities of a family unit. (is_adult: False)
    FAMILY_LIFE = "Family Life"

    # The story prominently features plant care and gardening. (is_adult: False)
    HORTICULTURE = "Horticulture"

    # Primary aim is to heal the audience through serene depictions of characters' daily lives. (is_adult: False)
    IYASHIKEI = "Iyashikei"

    # Centers around the experience of raising a child. (is_adult: False)
    PARENTHOOD = "Parenthood"

    #
    # SEXUAL CONTENT
    #

    # Features a character making an exaggerated orgasm face. (is_adult: True)
    AHEGAO = "Ahegao"

    # Features amputation or amputees. (is_adult: True)
    AMPUTATION = "Amputation"

    # Features sexual penetration of the anal cavity. (is_adult: True)
    ANAL_SEX = "Anal Sex"

    # Features the sexual depiction or stimulation of a character's armpits. (is_adult: True)
    ARMPITS = "Armpits"

    # Footjob; features stimulation of genitalia by feet. (is_adult: True)
    ASHIKOKI = "Ashikoki"

    # Features breath play. (is_adult: True)
    ASPHYXIATION = "Asphyxiation"

    # Features BDSM, with or without the use of accessories. (is_adult: True)
    BONDAGE = "Bondage"

    # Features the stimulation of male genitalia by breasts. (is_adult: True)
    BOOBJOB = "Boobjob"

    # A sexual act in which the cervix is visibly penetrated. (is_adult: True)
    CERVIX_PENETRATION = "Cervix Penetration"

    # Features a character with a partner shown being intimate with someone else consensually. (is_adult: True)
    CHEATING = "Cheating"

    # The stomach area expands outward like a balloon due to being filled specifically with semen. (is_adult: True)
    CUMFLATION = "Cumflation"

    # Features oral sex performed on female genitalia. (is_adult: True)
    CUNNILINGUS = "Cunnilingus"

    # Features oral sex where the majority of the erect male genitalia is inside another person's mouth, usually stimulating some gagging in the back of their throat. (is_adult: True)
    DEEPTHROAT = "Deepthroat"

    # Features a female character who has never had sexual relations (until now). (is_adult: True)
    DEFLORATION = "Defloration"

    # Features sexual intercourse with older men. (is_adult: True)
    DILF = "DILF"

    # A sexual act in which the vagina/anus are penetrated by two penises/toys. (is_adult: True)
    DOUBLE_PENETRATION = "Double Penetration"

    # Features a type of body modification designed to enhance sexual pleasure and intimacy, and/or decoratively adorns portions of the body considered sexual in nature. (is_adult: True)
    EROTIC_PIERCINGS = "Erotic Piercings"

    # Features the act of exposing oneself in public for sexual pleasure. (is_adult: True)
    EXHIBITIONISM = "Exhibitionism"

    # Features sexual ejaculation onto an individual's face. (is_adult: True)
    FACIAL = "Facial"

    # Features the sexual depiction or stimulation of a character's feet. (is_adult: True)
    FEET = "Feet"

    # Blowjob; features oral sex performed on male genitalia. (is_adult: True)
    FELLATIO = "Fellatio"

    # Female Dominance. Features sexual acts with a woman in a dominant position. (is_adult: True)
    FEMDOM = "Femdom"

    # Features vaginal or anal insertion of fingers. (is_adult: True)
    FINGERING = "Fingering"

    # A sexual activity that involves inserting one or more hands into the vagina or rectum. (is_adult: True)
    FISTING = "Fisting"

    # Features a female character with smaller-than-average breasts. (is_adult: True)
    FLAT_CHEST = "Flat Chest"

    # Features female characters with male genitalia. (is_adult: True)
    FUTANARI = "Futanari"

    # Features more than two participants engaged in sex simultaneously. (is_adult: True)
    GROUP_SEX = "Group Sex"

    # A sexual act in which the giver will grab the receivers hair and tug whilst giving pleasure from behind. (is_adult: True)
    HAIR_PULLING = "Hair Pulling"

    # Features the stimulation of genitalia by another's hands. (is_adult: True)
    HANDJOB = "Handjob"

    # Features characters in a master-slave relationship where one is the "owner" and the other is a "pet." (is_adult: True)
    HUMAN_PET = "Human Pet"

    # Portrays a character with a hypersexuality disorder, compulsive sexual behavior, or sex addiction. (is_adult: True)
    HYPERSEXUALITY = "Hypersexuality"

    # Features sexual or romantic relations between characters who are related by blood. (is_adult: True)
    INCEST = "Incest"

    # Features sexual or romantic relations among step, adopted, and other non-blood related family members. (is_adult: True)
    INSEKI = "Inseki"

    # Oral rape; features a character thrusting their genitalia or a phallic object into the mouth of another character. (is_adult: True)
    IRRUMATIO = "Irrumatio"

    # Features breast milk play and production. (is_adult: True)
    LACTATION = "Lactation"

    # Features a character with larger-than-average breasts. (is_adult: True)
    LARGE_BREASTS = "Large Breasts"

    # Features pregnant male characters in a sexual context. (is_adult: True)
    MALE_PREGNANCY = "Male Pregnancy"

    # Prominently features characters who get sexual pleasure from being hurt or controlled by others. (is_adult: True)
    MASOCHISM = "Masochism"

    # Features erotic stimulation of one's own genitalia or other erogenous regions. (is_adult: True)
    MASTURBATION = "Masturbation"

    # Features the sex position in which two partners face each other, with one of them thrusting downwards and the other's legs tucked up towards their head. (is_adult: True)
    MATING_PRESS = "Mating Press"

    # Features sexual intercourse with older women. (is_adult: True)
    MILF = "MILF"

    # Creampie; features sexual ejaculation inside of a character. (is_adult: True)
    NAKADASHI = "Nakadashi"

    # Netorare is what happens when the protagonist gets their partner stolen from them by someone else. It is a sexual fetish designed to cause sexual jealousy by way of having the partner indulge in sexual activity with someone other than the protagonist. (is_adult: True)
    NETORARE = "Netorare"

    # Features characters in a romantic relationship who agree to be sexually intimate with others. (is_adult: True)
    NETORASE = "Netorase"

    # Features the protagonist stealing the partner of someone else. The opposite of netorare. (is_adult: True)
    NETORI = "Netori"

    # Features a character who has sexual relations with both the mother and her daughter. (is_adult: True)
    OYAKODON = "Oyakodon"

    # Treating a participant as though they were a pet animal. Often involves a collar and possibly BDSM. (is_adult: True)
    PET_PLAY = "Pet Play"

    # Features characters who are paid for sexual favors. (is_adult: True)
    PROSTITUTION = "Prostitution"

    # Features sexual acts performed in public settings. (is_adult: True)
    PUBLIC_SEX = "Public Sex"

    # Features non-consensual sexual penetration. (is_adult: True)
    RAPE = "Rape"

    # Features oral sex performed on the anus. (is_adult: True)
    RIMJOB = "Rimjob"

    # Prominently features characters deriving pleasure, especially sexual gratification, from inflicting pain, suffering, or humiliation on others. (is_adult: True)
    SADISM = "Sadism"

    # Lots of feces. (is_adult: True)
    SCAT = "Scat"

    # A form of sexual activity between women in which the genitals are stimulated by being rubbed against one another. (is_adult: True)
    SCISSORING = "Scissoring"

    # Features objects that are designed to stimulate sexual pleasure. (is_adult: True)
    SEX_TOYS = "Sex Toys"

    # Features a character who has sexual relations with two sisters. (is_adult: True)
    SHIMAIDON = "Shimaidon"

    # Female ejaculation; features the expulsion of liquid from the female genitalia. (is_adult: True)
    SQUIRTING = "Squirting"

    # Pussyjob; features the stimulation of male genitalia by the thighs and labia majora of a female character. (is_adult: True)
    SUMATA = "Sumata"

    # Features consensual partner swapping between couples during sexual activities. (is_adult: True)
    SWAPPING_ = "Swapping "

    # Lots of sweat. (is_adult: True)
    SWEAT = "Sweat"

    # Features the long appendages most commonly associated with octopuses or squid, often sexually penetrating a character. (is_adult: True)
    TENTACLES = "Tentacles"

    # Features sexual acts between three people. (is_adult: True)
    THREESOME = "Threesome"

    # Features a male character who has never had sexual relations (until now). (is_adult: True)
    VIRGINITY = "Virginity"

    # Features a character being swallowed or swallowing another creature whole. (is_adult: True)
    VORE = "Vore"

    # Features a character who enjoys seeing the sex acts or sex organs of others. (is_adult: True)
    VOYEUR = "Voyeur"

    # Features sexual situations involving urine. (is_adult: True)
    WATERSPORTS = "Watersports"

    # Features a character who has a sexual attraction for non-human animals. (is_adult: True)
    ZOOPHILIA = "Zoophilia"

    #
    # THEME-FANTASY
    #

    # Features character(s) who practice alchemy. (is_adult: False)
    ALCHEMY = "Alchemy"

    # Centers around individuals swapping bodies with one another. (is_adult: False)
    BODY_SWAPPING = "Body Swapping"

    # Features characters using training, often martial arts-related, and other special methods to cultivate qi (a component of traditional Chinese philosophy, described as "life force") and gain strength or immortality. (is_adult: False)
    CULTIVATION = "Cultivation"

    # Features a character, object or area that has been cursed, usually by a malevolent supernatural force. (is_adult: False)
    CURSES = "Curses"

    # Involving religious methods of vanquishing youkai, demons, or other supernatural entities. (is_adult: False)
    EXORCISM = "Exorcism"

    # This work tells a fairy tale, centers around fairy tales, or is based on a classic fairy tale. (is_adult: False)
    FAIRY_TALE = "Fairy Tale"

    # Prominently features character or costume transformations which often grant special abilities. (is_adult: False)
    HENSHIN = "Henshin"

    # Features characters being transported into an alternate world setting and having to adapt to their new surroundings. (is_adult: False)
    ISEKAI = "Isekai"

    # Prominently features giant monsters. (is_adult: False)
    KAIJU = "Kaiju"

    # Prominently features magical elements or the use of magic. (is_adult: False)
    MAGIC = "Magic"

    # Prominently features mythological elements, especially those from religious or cultural tradition. (is_adult: False)
    MYTHOLOGY = "Mythology"

    # When the dead are summoned as spirits, skeletons, or the undead, usually for the purpose of gaining information or to be used as a weapon. (is_adult: False)
    NECROMANCY = "Necromancy"

    # Features a character from a fantasy world who is transported into a modern day setting. (is_adult: False)
    REVERSE_ISEKAI = "Reverse Isekai"

    # Features character(s) who changes one's appearance or form. (is_adult: False)
    SHAPESHIFTING = "Shapeshifting"

    # Prominently features technology and designs inspired by 19th-century industrial steam-powered machinery. (is_adult: False)
    STEAMPUNK = "Steampunk"

    # Prominently features characters with special abilities that allow them to do what would normally be physically or logically impossible. (is_adult: False)
    SUPER_POWER = "Super Power"

    # Prominently features super-powered humans who aim to serve the greater good. (is_adult: False)
    SUPERHERO = "Superhero"

    # Chinese fiction concerning the adventures of martial artists in Ancient China. (is_adult: False)
    WUXIA = "Wuxia"

    # Prominently features supernatural creatures from Japanese folklore. (is_adult: False)
    YOUKAI = "Youkai"

    #
    # CAST-MAIN CAST
    #

    # Features a protagonist who lacks conventional heroic attributes and may be considered a borderline villain. (is_adult: False)
    ANTI_HERO = "Anti-Hero"

    # The protagonist is either over 60 years of age, has an elderly appearance, or, in the case of non-humans, is considered elderly for their species. (is_adult: False)
    ELDERLY_PROTAGONIST = "Elderly Protagonist"

    # Features a large cast of characters with (almost) equal screen time and importance to the plot. (is_adult: False)
    ENSEMBLE_CAST = "Ensemble Cast"

    # At least one family member of the MC intentionally distances themselves or a family distances themselves from a person related to the MC. (is_adult: False)
    ESTRANGED_FAMILY = "Estranged Family"

    # Main character is female. (is_adult: False)
    FEMALE_PROTAGONIST = "Female Protagonist"

    # Main character is male. (is_adult: False)
    MALE_PROTAGONIST = "Male Protagonist"

    # Main cast is mostly composed of characters above a high school age. (is_adult: False)
    PRIMARILY_ADULT_CAST = "Primarily Adult Cast"

    # Main cast is mostly composed animal or animal-like characters. (is_adult: False)
    PRIMARILY_ANIMAL_CAST = "Primarily Animal Cast"

    # Main cast is mostly composed of characters below a high school age. (is_adult: False)
    PRIMARILY_CHILD_CAST = "Primarily Child Cast"

    # Main cast is mostly composed of female characters. (is_adult: False)
    PRIMARILY_FEMALE_CAST = "Primarily Female Cast"

    # Main cast is mostly composed of male characters. (is_adult: False)
    PRIMARILY_MALE_CAST = "Primarily Male Cast"

    # Main cast is mostly composed of teen characters. (is_adult: False)
    PRIMARILY_TEEN_CAST = "Primarily Teen Cast"

    #
    # THEME-ACTION
    #

    # Centers around the sport of archery, or prominently features the use of archery in combat. (is_adult: False)
    ARCHERY = "Archery"

    # Centers around a fierce group competition, often violent and with only one winner. (is_adult: False)
    BATTLE_ROYALE = "Battle Royale"

    # Prominently features characters infiltrating an organization in order to steal sensitive information. (is_adult: False)
    ESPIONAGE = "Espionage"

    # Prominently features a character evading capture by an individual or organization. (is_adult: False)
    FUGITIVE = "Fugitive"

    # Prominently features the use of guns in combat. (is_adult: False)
    GUNS = "Guns"

    # Centers around the use of traditional hand-to-hand combat. (is_adult: False)
    MARTIAL_ARTS = "Martial Arts"

    # Prominently features the use of spears in combat. (is_adult: False)
    SPEARPLAY = "Spearplay"

    # Prominently features the use of swords in combat. (is_adult: False)
    SWORDPLAY = "Swordplay"

    #
    # THEME-OTHER-ORGANISATIONS
    #

    # Centers around characters who murder people as a profession. (is_adult: False)
    ASSASSINS = "Assassins"

    # Prominently features a group of people who commit crimes for illicit or violent purposes. (is_adult: False)
    CRIMINAL_ORGANIZATION = "Criminal Organization"

    # Features a social group with unorthodox religious, spiritual, or philosophical beliefs and practices. (is_adult: False)
    CULT = "Cult"

    # Centered around the life and activities of rescuers specialised in firefighting. (is_adult: False)
    FIREFIGHTERS = "Firefighters"

    # Centers around gang organizations. (is_adult: False)
    GANGS = "Gangs"

    # Centered around Italian organised crime syndicates. (is_adult: False)
    MAFIA = "Mafia"

    # Centered around the life and activities of military personnel. (is_adult: False)
    MILITARY = "Military"

    # Centers around the life and activities of law enforcement officers. (is_adult: False)
    POLICE = "Police"

    # Centered around Chinese organised crime syndicates. (is_adult: False)
    TRIADS = "Triads"

    # Centered around Japanese organised crime syndicates. (is_adult: False)
    YAKUZA = "Yakuza"

    #
    # THEME-OTHER-VEHICLE
    #

    # Regarding the flying or operation of aircraft. (is_adult: False)
    AVIATION = "Aviation"

    # Centers around the use of automotive vehicles. (is_adult: False)
    CARS = "Cars"

    # Prominently features mopeds. (is_adult: False)
    MOPEDS = "Mopeds"

    # Prominently features the use of motorcycles. (is_adult: False)
    MOTORCYCLES = "Motorcycles"

    # Prominently features the use of sea-based transportation vessels. (is_adult: False)
    SHIPS = "Ships"

    # Prominently features the use of tanks or other armoured vehicles. (is_adult: False)
    TANKS = "Tanks"

    # Prominently features trains. (is_adult: False)
    TRAINS = "Trains"

    #
    # THEME-ARTS-MUSIC
    #

    # Main cast is a group of musicians. (is_adult: False)
    BAND = "Band"

    # Centers on the musical style of classical, not to be applied to anime that use classical in its soundtrack. (is_adult: False)
    CLASSICAL_MUSIC = "Classical Music"

    # Centers around the art of dance. (is_adult: False)
    DANCING = "Dancing"

    # Centers on the musical style of hip-hop, not to be applied to anime that use hip-hop in its soundtrack. (is_adult: False)
    HIP_HOP_MUSIC = "Hip-hop Music"

    # Centers on the musical style of jazz, not to be applied to anime that use jazz in its soundtrack. (is_adult: False)
    JAZZ_MUSIC = "Jazz Music"

    # Centers on the musical style of metal, not to be applied to anime that use metal in its soundtrack. (is_adult: False)
    METAL_MUSIC = "Metal Music"

    # Features a performance that combines songs, spoken dialogue, acting, and dance. (is_adult: False)
    MUSICAL_THEATER = "Musical Theater"

    # Centers on the musical style of rock, not to be applied to anime that use rock in its soundtrack. (is_adult: False)
    ROCK_MUSIC = "Rock Music"

    #
    # SETTING-SCENE
    #

    # Partly or completely set in a bar. (is_adult: False)
    BAR = "Bar"

    # Features characters attending a boarding school. (is_adult: False)
    BOARDING_SCHOOL = "Boarding School"

    # Features the recreational activity of camping, either in a tent, vehicle, or simply sleeping outdoors. (is_adult: False)
    CAMPING = "Camping"

    # Prominently features a circus. (is_adult: False)
    CIRCUS = "Circus"

    # Story prominently takes place near the beach or around a coastal area/town. Setting is near the ocean. (is_adult: False)
    COASTAL = "Coastal"

    # Partly or completely set in a college or university. (is_adult: False)
    COLLEGE = "College"

    # Prominently features a desert environment. (is_adult: False)
    DESERT = "Desert"

    # Prominently features a dungeon environment. (is_adult: False)
    DUNGEON = "Dungeon"

    # Partly or completely set in a country outside the country of origin. (is_adult: False)
    FOREIGN = "Foreign"

    # Partially or completely set in an Inn or Hotel. (is_adult: False)
    INN = "Inn"

    # Predominantly features a convenience store. (is_adult: False)
    KONBINI = "Konbini"

    # It focuses on catastrophic events of natural origin, such as earthquakes, tsunamis,  volcanic eruptions, and severe storms. These works often present situations of extreme danger in which the characters struggle to survive and overcome the adversity. (is_adult: False)
    NATURAL_DISASTER = "Natural Disaster"

    # Features people who work in a business office. (is_adult: False)
    OFFICE = "Office"

    # Centers around hiking, camping or other outdoor activities. (is_adult: False)
    OUTDOOR_ACTIVITIES = "Outdoor Activities"

    # Partly or completely set in a prison. (is_adult: False)
    PRISON = "Prison"

    # Features a business that prepares and serves food and drinks to customers. Also encompasses cafes and bistros. (is_adult: False)
    RESTAURANT = "Restaurant"

    # Partly or completely set in the countryside. (is_adult: False)
    RURAL = "Rural"

    # Partly or completely set in a primary or secondary educational institution. (is_adult: False)
    SCHOOL = "School"

    # Partly or completely set in a school club scene. (is_adult: False)
    SCHOOL_CLUB = "School Club"

    # Prominently or partially set in a snowy environment. (is_adult: False)
    SNOWSCAPE = "Snowscape"

    # Partly or completely set in a city. (is_adult: False)
    URBAN = "Urban"

    # Predominantly features a location with little to no human activity, such as a deserted island, a jungle, or a snowy mountain range. (is_adult: False)
    WILDERNESS = "Wilderness"

    # Centers around the activities of a certain occupation. (is_adult: False)
    WORK = "Work"

    #
    # THEME-GAME
    #

    # Centers around characters playing board games. (is_adult: False)
    BOARD_GAME = "Board Game"

    # Prominently features professional video game competitions, tournaments, players, etc. (is_adult: False)
    E_SPORTS = "E-Sports"

    # Centers around characters playing video games. (is_adult: False)
    VIDEO_GAMES = "Video Games"

    #
    # THEME-DRAMA
    #

    # Prominently features the use of force for intimidation, often in a school setting. (is_adult: False)
    BULLYING = "Bullying"

    # Contains conflict born between the different social classes. Generally between an dominant elite and a suffering oppressed group. (is_adult: False)
    CLASS_STRUGGLE = "Class Struggle"

    # Centers around a character's transition from childhood to adulthood. (is_adult: False)
    COMING_OF_AGE = "Coming of Age"

    # Contains one or more factions controlling or attempting to control the world from the shadows. (is_adult: False)
    CONSPIRACY = "Conspiracy"

    # Utilizes a horrifying depiction of ecology to explore man and its relationship with nature. (is_adult: False)
    ECO_HORROR = "Eco-Horror"

    # When two characters enter a fake relationship that mutually benefits one or both involved. (is_adult: False)
    FAKE_RELATIONSHIP = "Fake Relationship"

    # Characters in these series take on the responsibility of running a town or kingdom, whether they take control of an existing one, or build their own from the ground up. (is_adult: False)
    KINGDOM_MANAGEMENT = "Kingdom Management"

    # Prominently features the recovery of a character who became incapable of social life or work. (is_adult: False)
    REHABILITATION = "Rehabilitation"

    # Prominently features a character who aims to exact punishment in a resentful or vindictive manner. (is_adult: False)
    REVENGE = "Revenge"

    # The act or an instance of taking or attempting to take one's own life voluntarily and intentionally. (is_adult: False)
    SUICIDE = "Suicide"

    # Centers around tragic events and unhappy endings. (is_adult: False)
    TRAGEDY = "Tragedy"

    #
    # THEME-GAME-CARD & BOARD GAME
    #

    # Centers around individuals competing in card games. (is_adult: False)
    CARD_BATTLE = "Card Battle"

    # Centered around the game of Go. (is_adult: False)
    GO = "Go"

    # Centers around the game of karuta. (is_adult: False)
    KARUTA = "Karuta"

    # Centered around the game of mahjong. (is_adult: False)
    MAHJONG = "Mahjong"

    # Centers around the game of poker or its variations. (is_adult: False)
    POKER = "Poker"

    # Centers around the game of shogi. (is_adult: False)
    SHOGI = "Shogi"

    #
    # THEME-SCI-FI
    #

    # Set in a future of advanced technological and scientific achievements that have resulted in social disorder. (is_adult: False)
    CYBERPUNK = "Cyberpunk"

    # Centers around space warfare, advanced technology, chivalric romance and adventure. (is_adult: False)
    SPACE_OPERA = "Space Opera"

    # A character is stuck in a repetitive cycle that they are attempting to break out of. This is distinct from a manipulating time of their own choice. (is_adult: False)
    TIME_LOOP = "Time Loop"

    # Prominently features time-traveling or other time-warping phenomena. (is_adult: False)
    TIME_MANIPULATION = "Time Manipulation"

    # Prominently features elements that resemble special effects in Japanese live-action shows (is_adult: False)
    TOKUSATSU = "Tokusatsu"

    #
    # DEMOGRAPHIC
    #

    # Target demographic is adult females. (is_adult: False)
    JOSEI = "Josei"

    # Target demographic is young children. (is_adult: False)
    KIDS = "Kids"

    # Target demographic is adult males. (is_adult: False)
    SEINEN = "Seinen"

    # Target demographic is teenage and young adult females. (is_adult: False)
    SHOUJO = "Shoujo"

    # Target demographic is teenage and young adult males. (is_adult: False)
    SHOUNEN = "Shounen"

    #
    # SETTING
    #

    # Prominently features a country that is ruled by a Queen or a society that is dominated by female inheritance. (is_adult: False)
    MATRIARCHY = "Matriarchy"

    #
    # THEME-COMEDY
    #

    # Features deliberate exaggeration of popular tropes or a particular genre to comedic effect. (is_adult: False)
    PARODY = "Parody"

    # Prominently features the use of comedy or ridicule to expose and criticise social phenomena. (is_adult: False)
    SATIRE = "Satire"

    # Prominently features comedy based on deliberately clumsy actions or embarrassing events. (is_adult: False)
    SLAPSTICK = "Slapstick"

    # Prominently features comedic moments that defy casual reasoning, resulting in illogical events. (is_adult: False)
    SURREAL_COMEDY = "Surreal Comedy"

    #
    # THEME-SCI-FI-MECHA
    #

    # Prominently features mechanical designs loosely influenced by real-world robotics. (is_adult: False)
    REAL_ROBOT = "Real Robot"

    # Prominently features large robots often piloted by hot-blooded protagonists. (is_adult: False)
    SUPER_ROBOT = "Super Robot"
